sky:
  wechat:
#    小程序ID
    appid: wx5ee93b12f76160ba
#     小程序密钥
    secret: b684309c0cbd9a705355df041b64042b

#    商户号
    mchid : 1561414331
#    商户API证书的证书序列号
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    商户私钥文件
    privateKeyFilePath: D:\apiclient_key.pem
#    证书解密的密钥
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    平台证书文件
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
#    支付成功的回调地址
    notifyUrl: https://10d147e5.r10.cpolar.top/wxpay/paySuccess
#    支付失败的回调地址
    refundNotifyUrl: https://10d147e5.r10.cpolar.top/wxpay/refundSuccess
  redis:
    host: 192.168.153.131
    port: 6379
    password: 123123
    database: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123123

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSGRg6JWd19RHfmfaAT
    access-key-secret: SWxcFkLagdCOfvOU1RBmul9nnICsdU
    bucket-name: cc-sky-img