sky:
  wechat:
    appid: wx5ee93b12f76160ba
    secret: b684309c0cbd9a705355df041b64042b
  redis:
    host: 192.168.153.131
    port: 6379
    password: 123123
    database: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123123

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSGRg6JWd19RHfmfaAT
    access-key-secret: SWxcFkLagdCOfvOU1RBmul9nnICsdU
    bucket-name: cc-sky-img